### ISSUE TITLE
VirtualCodebase fails with Python 3.9

### ISSUE THREAD

**Issue by tdruez** [nexB/commoncode#6]
The `json.load` call in `VirtualCodebase._get_scan_data_helper` provide a `encoding='utf-8'` argument that was removed in Python 3.9. See https://github.com/nexB/commoncode/blob/main/src/commoncode/resource.py#L762

https://docs.python.org/3.8/library/json.html#json.loads
> Deprecated since version 3.1, will be removed in version 3.9: encoding keyword argument.

This was simply ignored by all Python 3 version until 3.9 that now raise a TypeError.

We should simply remove this argument.

```
Traceback (most recent call last):
  File "lib/python3.9/site-packages/commoncode/resource.py", line 1464, in __init__
    scan_data = self._get_scan_data(location)
  File "lib/python3.9/site-packages/commoncode/resource.py", line 1507, in _get_scan_data
    return self._get_scan_data_helper(location)
  File "lib/python3.9/site-packages/commoncode/resource.py", line 1478, in _get_scan_data_helper
    scan_data = json.load(f, object_pairs_hook=OrderedDict, encoding='utf-8')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by pombredanne** [comment]
All merged. Thank you ++
